/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { WebTwain } from "dwt/dist/types/WebTwain";
export { WebTwain } from "dwt/dist/types/WebTwain";
export namespace Components {
    interface PdfViewer {
        "height"?: string;
        "license"?: string;
        "showthumbnailviewer"?: string;
        "toggleThumbnailViewer": () => Promise<void>;
        "url"?: string;
        "width"?: string;
    }
}
export interface PdfViewerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPdfViewerElement;
}
declare global {
    interface HTMLPdfViewerElement extends Components.PdfViewer, HTMLStencilElement {
    }
    var HTMLPdfViewerElement: {
        prototype: HTMLPdfViewerElement;
        new (): HTMLPdfViewerElement;
    };
    interface HTMLElementTagNameMap {
        "pdf-viewer": HTMLPdfViewerElement;
    }
}
declare namespace LocalJSX {
    interface PdfViewer {
        "height"?: string;
        "license"?: string;
        "onWebTWAINReady"?: (event: PdfViewerCustomEvent<WebTwain>) => void;
        "showthumbnailviewer"?: string;
        "url"?: string;
        "width"?: string;
    }
    interface IntrinsicElements {
        "pdf-viewer": PdfViewer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pdf-viewer": LocalJSX.PdfViewer & JSXBase.HTMLAttributes<HTMLPdfViewerElement>;
        }
    }
}
